config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    root 'sessions#home'
    get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

    get '/signup', to: 'users#new'
    post '/signup', to: 'users#signup'

    get '/login', to: 'sessions#login'
    post '/signing', to: 'sessions#signing'

    delete '/logout', to: 'sessions#logout'

    get 'search', to: 'players#search'
    # get 'authors/:id/posts', to: 'authors#posts_index'
    # get 'authors/:id/posts/:post_id', to: 'authors#post'

    resources :players, only: [:new, :create, :index]
    
    resources :teams, only: [:show] do
      resources :players, shallow: true
    end
    
    resources :countries, only: [:show]
    resources :users

    # get 'about', to: 'static#about'
    # resources :posts, only: [:index, :show, :new, :create, :edit, :update, :delete]

    # get'/logout', to: 'sessions#logout'  #handling get logout from users
end

app/models/player.rb
class Player < ApplicationRecord

    belongs_to :coach, :class_name => "User"
    belongs_to :team 
    validates :name, :age, :position, :number, presence: true
    validates_associated :team, :message => "name and country name can't be empty"
    # validates team_attributes: [:name, :country_name]

    # accepts_nested_attributes_for :team

    scope :order_alphabetically, -> {order(name: :asc) }

    
    def team_attributes=(team_attributes)
        # team _attributes = {"name"=>"", "country_name"=>""}
        self.team = Team.find_or_create_by(name: team_attributes[:name].capitalize)
        self.team.update(name: team_attributes[:name].capitalize, country_name: team_attributes[:country_name].capitalize)
    end

    def self.search(params)
        self.where("name LIKE ?", "%"+ params+"%")[0]
    end
    
   
    # def team_attributes
    #     # self.team ? self.team.name : nil
    # end

    # scope :order_by_popularity, -> { Workout.left_joins(:trainings).group(:id).order("count(trainings.workout_id) desc") }
    # scope :out_of_print_and_expensive, -> { out_of_print.where('price > 500') }
    # accepts_nested_attributes_for :team
    # validates :team, :name, :age, :position, :number,  presence: true

    # def team_name=(name)
    #     self.team = Team.find_or_create_by(name: name)
    # end
   
    # def team_name
    #     self.team ? self.team.name : nil
    # end

    # def self.set_team_and_country(team_name, team_name)
    #     @country = Country.create(name: country_name)
    #     @team = @country.teams.build(name: team_name)
    #     @team.save
    #     @team
    # end
    
    


    # belongs_to :brand
    # belongs_to :user
    # has_many :customizations
    # accepts_nested_attributes_for :brand #brand_attributes=

    # def brand_attributes=(hash_of_attributes)
    #     # byebug
    #     if !hash_of_attributes["name"].blank? && !hash_of_attributes["year_founded"].blank?
    #         self.brand = Brand.find_or_create_by(hash_of_attributes)
            
    #     end
    # end

    # validates :condition, presence: true
    # validates :price, numericality: {greater_than: 0, less_than: 5000}
    # validates :color, presence: true, two_word: true, uniqueness: {scope: [:brand, :price]}


    # scope :order_alphabetically, -> {order(age: :age > 30)}
    # scope :order_alphabetically, -> {order(name: :asc) }
    # scope :order_by_condition, -> {order(:condition)}
    # scope :color_selector, -> (color) {where('color == ?', color)}
      
    # def name_and_color 
    #       "#{self.brand.name} - #{self.color} - #{self.condition}"
    #   end
  
     
  
    #   def self.order_by_price 
    #       self.order(price: :desc)
    #   end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :redirect_if_not_logged_in?
    before_action :find_player, only: [:show, :update, :edit, :destroy]
    before_action :redirect_if_not_authorized, only: [:show, :update, :edit, :destroy]
    # skip_before_action :redirect_if_not_logged_in, only: [:new, :create]


    def new
        if params[:team_id] && @team = Team.find_by_id(params[:team_id])
            if current_user.teams.include? @team
                @player = @team.players.build
            else
                flash[:message] = "you have been redirected"
                redirect_to players_path
            end
        else
            @player = Player.new
            @player.build_team
        end
    end
    
    def index
        if params[:team_id] && @team = Team.find_by_id(params[:team_id])
            if current_user.teams.include? @team
               @players = @team.players
            else
                flash[:message] = "you have been redirected"
                redirect_to players_path
            end
        else
            @players = Player.order_alphabetically
        end
    end


    def show
    end

    def edit
    end

    def search
        if params[:q].blank?  
            redirect_to(players_path, alert: "Empty field!") 
        else 
        @player = Player.search(params[:q])
        render :'players/show'
        end
    end
    

    
    def create
    
        @player = Player.new(player_params)
        if @player.save
            redirect_to player_path(@player)
        else
            render :new
        end
    end

    def update
        @player.update(player_params)
        redirect_to player_path(@player)
    end 

    def destroy
        @player = Player.find(params[:id])
        @player.destroy
        redirect_to players_path, :notice => "Your player has been deleted"
    end




    private 



    def player_params
        params.require(:player).permit(:name, :age, :team_id, :position, :number, :coach_id, team_attributes: [:name, :country_name])
    end

    def find_player 
        @player = Player.find_by_id(params[:id])
    end  
    
    def redirect_if_not_authorized
        if @player.coach != current_user
          redirect_to players_path 
        end 
    end
end

app/views/players/_form.html.erb
 <%= flash[:message]%><br><br>

      <%= f.label :'player name' %>
      <%= f.text_field :name%><br><br>
      
      <%= f.label :age %>
      <%= f.text_field :age%><br><br>
   
      <%= f.label :position%>
      <%= f.text_field :position%><br><br>
   
      <%= f.label :number%>
      <%= f.text_field :number%><br><br>

      <%= f.hidden_field :coach_id, value: current_user.id %>
      
      

app/views/players/edit.html.erb
<div class= "container" style="background-color: #548CA8">
  
  <h1>player Edit Form </h1>

  <%= render partial: "users/errors", locals: {object: @player} %>

  <%= form_for @player do |f| %>

      <%= render partial: "form", locals: {f: f} %>
    
    <br><br><%= f.submit %><br><br>
  <% end %>


  <%=session_home%><br>
  <%=navigation_helper%><br>
</div>  

app/views/players/index.html.erb
<div class= "container" style="background-color: #548CA8"> 
    <br>


    
    <h3><%= flash[:message]%></h3>

    <h1>Welcome <%=current_user.user_name%> to your Players page</h1><br>

    <%= form_tag("/search", :method => "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search") %>
    <% end %>

    <%if current_user.players.size == 0%>
    <h3>you don't have any player yet</h3>
    <%else%>
        <ul>
        <% @players.each do |p| %>
            <%if p.coach ==  current_user%>
                <li>
                    <%= link_to p.name, player_path(p)%>
                </li><br>
            <%end%>
            <% end %>
        </ul>
    <%end%>

    <%=button_to "Add player", new_player_path, method: 'get' %><br>
    <%=navigation_helper%><br>
</div>

app/views/players/new.html.erb
<h1>Player Form </h1>
<div class= "container" style="background-color: #548CA8">
    <%= render partial: "users/errors", locals: {object: @player} %>


    <%= form_for @player do |f| %>

    <%= render partial: "form", locals: {f: f} %>

    <%if @team%>
    <%= f.hidden_field :team_id, value: @team.id%>
    <%else%>

        <h3>Add team</h3>

        <%= f.fields_for :team do |t| %>

        <%= t.label :name %>
        <%= t.text_field :name %><br><br>

        <%= t.label :country_name %>
        <%= t.text_field :country_name %>
        <% end %>
    <%end%>


<br><br><br><%= f.submit %><br><br>

<% end %>

<%=session_home%><br>
<%=navigation_helper%><br>
</div>

app/views/players/show.html.erb
<div class= "container" style="background-color: #548CA8">

    <h1>Player show page</h1>
    <hr>
    <h2>Name: <%= @player.name %></h2>

    <h2>Age: <%=@player.age%>

    <h2>Position: <%=@player.position%></h2>

    <h2>Number: <%= @player.number %></h2>

    <h2>Coach: <%= @player.coach.user_name %>  </h2>

    <h2>Team: <%= link_to @player.team.name, team_path(@player.team)%><br><br>

    <%=home_nav_button%><br>
    <%=logout_nav_button%><br>
    <%=edit_nav_button(@player)%><br>

    <%= button_to "Delete", @player, :confirm => "Are you sure?", :method => :delete %><br>
   
</div>    